Repository Acousticakku/Hacktoberfest2023, pull requests merged in 2023-10, with the labels that each got.

#5 Add Kadane's Algorithm implementation
  Dsa/Java/MaximumSubarray.java
Labels: hacktoberfest-accepted

#4 Added a leet code hard level DSA Question with solution.
  Dsa/Java/MedianOf2Arrays.java
Labels: hacktoberfest-accepted

#3 Create UniqueMinimumProductSubarra.java
  Dsa/Java/UniqueMinimumProductSubarra.java
Labels: hacktoberfest-accepted

#6 Create dsa-recursion.java
  Dsa/Java/dsa-recursion.java
Labels: hacktoberfest-accepted

#8 Create duplicateRemover.java
  Dsa/Java/duplicateRemover.java
Labels: hacktoberfest-accepted

#9 Create Recursion.java
  Dsa/Java/Recursion.java
Labels: hacktoberfest-accepted

#10 Create linear.java
  Dsa/Java/linear.java
Labels: hacktoberfest-accepted

#12 Create MergeTwoSortedArray
  MergeTwoSortedArray
Labels: Hacktoberfest2023, hacktoberfest-accepted, Hacktoberfest

#14 SkipList.java :- Add as many possible but valid DSA question in any language just keep in mind you have to maintain the folders #1
  Dsa/Java/SkipList.java
Labels: hacktoberfest-accepted

#15 Create TriesAlgorithm.java
  TriesAlgorithm.java
Labels: hacktoberfest-accepted

#16 infix expression to PREFIX Expression
  Dsa/Java/infixToPrefix.java
  Dsa/Java/postfixEvaluation.java
Labels: hacktoberfest-accepted

#17 Added DijkstraAlgorithm.java
  Dsa/Java/DijkstraAlgorithm.java
Labels: hacktoberfest-accepted

#19 Create Merge_Intervals.java
  Dsa/Java/Merge_Intervals.java
Labels: hacktoberfest-accepted

#18 Folderc++Added
  Dsa/C++/AVL.cpp
  Dsa/C++/Array.cpp
  Dsa/C++/BFS.cpp
  Dsa/C++/BST.cpp
  Dsa/C++/BasicArray.cpp
  Dsa/C++/CDLL.cpp
  Dsa/C++/CLL.cpp
  Dsa/C++/DFS.cpp
  Dsa/C++/DLL.cpp
  Dsa/C++/Driver.cpp
  Dsa/C++/Driver.exe
  Dsa/C++/DynArray.cpp
  Dsa/C++/Heap.cpp
  Dsa/C++/Polynomial.cpp
  Dsa/C++/PriorityArray.cpp
  Dsa/C++/PriorityQueue.cpp
  Dsa/C++/QueueArrays.cpp
  Dsa/C++/QueueDLL.cpp
  Dsa/C++/QueueList.cpp
  Dsa/C++/Recursion.cpp
  Dsa/C++/SLL.cpp
  Dsa/C++/SLLEXTENDED.cpp
  Dsa/C++/STACKTEMP.cpp
  Dsa/C++/StackArray.cpp
  Dsa/C++/StackList.cpp
  Dsa/C++/graphlist.cpp
  Dsa/C++/graphmatrix.cpp
  Dsa/C++/sorting.cpp
Labels: good first issue, hacktoberfest-accepted

#20 Bhushan chanore patch 1
  Dsa/Java/mergesort.java
Labels: hacktoberfest-accepted

#22 Create Quicksort.java
  Dsa/Java/Quicksort.java
Labels: hacktoberfest-accepted
